---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: go-app-client
  namespace: monitoring
  labels:
    prometheus: devops
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: go-app-client
  # you have to implement prometheus metrics in order to see the metrics of the pod
  podMetricsEndpoints:
    - port: metrics
