---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-app-client
  namespace: default
  labels:
    prometheus: devops
spec:
  endpoints:
    - port: http-metrics
      interval: 60s
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      service: go-app
