apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
      prometheus: devops
  template:
    metadata:
      labels:
        app: go-app
        prometheus: devops
    spec:
      containers:
      - name: go-app
        image: quickybooster/test-go-stdlib:1.0.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
