apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      prometheus: devops
  template:
    metadata:
      labels:
        app: go-app
        prometheus: devops
    spec:
      containers:
        - name: go-app
          image: quickybooster/go-app:2.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 2Gi
              cpu: "2"
            limits:
              memory: 2Gi
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - go-stdlib-app
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: default
  labels:
    service: go-app
spec:
  type: NodePort
  # type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 32000
  selector:
    app: go-app
